### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by GreyGnome** [snuq/Snu-Photo-Manager#4]
Hello,
What license are you using to release this under?

Thanks.

**Comment by snuq** [comment]
I actually havnt thought about this yet...

**Comment by Sires0** [comment]
Suggestions:
MIT - Very permissime
GPL 3 - Makes sure freedoom will always be a thing in your project
Apache - Another good license :P

Those are just some I know and love

**Comment by snuq** [comment]
Settled on GPL, one of the libraries I use (and ffmpeg) are gpl, so I think that's pretty much my only option anyway.
