### ISSUE TITLE
Deprecated Listview Needs To Be Replaced with Recycleview

### ISSUE THREAD

**Issue by eruber** [snuq/Snu-Photo-Manager#6]
[INFO   ] [Logger      ] Record log in C:\Users\ER\.kivy\logs\kivy_19-06-02_29.txt
[INFO   ] [Kivy        ] v1.11.0
[INFO   ] [Kivy        ] Installed at "D:\Devel\_python\_kivy\example-apps\Snu-Photo-Manager-master\SNU_PHOTO_VENV\lib\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "D:\Devel\_python\_kivy\example-apps\Snu-Photo-Manager-master\SNU_PHOTO_VENV\Scripts\python.exe"
[INFO   ] [deps        ] Successfully imported "kivy_deps.gstreamer" 0.1.17
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.1.12
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.1.22
[INFO   ] [Factory     ] 184 symbols loaded
[INFO   ] [ImageLoaderFFPy] Using ffpyplayer 4.2.0
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_ffpyplayer, img_gif
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.6.0 NVIDIA 430.64'>
[INFO   ] [GL          ] OpenGL vendor <b'NVIDIA Corporation'>
[INFO   ] [GL          ] OpenGL renderer <b'GeForce GTX 980/PCIe/SSE2'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60 NVIDIA'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: sdl2 
Traceback (most recent call last):
   File "main.py", line 84, in <module>
     from kivy.uix.listview import ListView, ListItemButton
 ModuleNotFoundError: No module named 'kivy.uix.listview'

Kivy has repalced listview with recycleview.

**Comment by snuq** [comment]
Use the latest master version for now. this and a couple other issues with the latest kivy and python are fixed.  Im working on a release currently that will have these fixes, have a couple features to finish up first.
