### ISSUE TITLE
unable to set a database dictionaries on  OSMojave

### ISSUE THREAD

**Issue by Stephenfang51** [snuq/Snu-Photo-Manager#7]
Dear Sir

your work is excellent !
but I have met the issue about the first step "set a database dictionaries", the "add" button can't be press down. 

My OS is  OSMojave

Thanks !

**Comment by snuq** [comment]
Hmm, unfortunately, I don't have an osx box to test anything on... 
First up, are you using the latest master?
If so, what exactly do you mean about the button not being able to press down? 
    1. it is greyed out and wont respond to presses
    2. it presses but nothing happens
    3. it looks normal, but wont respond to clicks at all

Also, does the ok button work?

Would you be able to run from a console and copy/paste any output from that (make sure you click the button before copy/pasting)?

**Comment by GavinGrayCT** [comment]
Hi
I have the same problem.

- Windows 10
- Python 3.7.4
- Running Snu PhotoManager as downloaded from PyCharm IDE project with a venv
- Database Directories pop up.
-     "You must set at least one data base directory" ...
-     When I click the "+", I get another popup ("Database Directories") with directories shown. Whatever I then do, the "Add" button remains disabled. In the kv def in filebrowser.py there is the rule "disabled: not root.target_selected or not (root.export_mode and len(root.file) > 0)" and I cannot see it enabled anywhere.

Kivy beginner

**Comment by snuq** [comment]
Ah! I was looking at the wrong button, I thought the bug was referring to the "+" button in the database directories dialog! I had messed up on the button disable logic, it should be fixed now in the repo, ill be recompiling the app and uploading fixed copies soon.

Also, thank you Gavin for tracking down the line that has the error, made it very quick to fix.
